// Generated by gencpp from file exp_excavator/JointStateMachineArduino.msg
// DO NOT EDIT!


#ifndef EXP_EXCAVATOR_MESSAGE_JOINTSTATEMACHINEARDUINO_H
#define EXP_EXCAVATOR_MESSAGE_JOINTSTATEMACHINEARDUINO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exp_excavator
{
template <class ContainerAllocator>
struct JointStateMachineArduino_
{
  typedef JointStateMachineArduino_<ContainerAllocator> Type;

  JointStateMachineArduino_()
    : boomP(0.0)
    , armP(0.0)
    , boomV(0.0)
    , armV(0.0)
    , boomI(0.0)
    , armI(0.0)
    , boomMode(0)
    , armMode(0)  {
    }
  JointStateMachineArduino_(const ContainerAllocator& _alloc)
    : boomP(0.0)
    , armP(0.0)
    , boomV(0.0)
    , armV(0.0)
    , boomI(0.0)
    , armI(0.0)
    , boomMode(0)
    , armMode(0)  {
  (void)_alloc;
    }



   typedef float _boomP_type;
  _boomP_type boomP;

   typedef float _armP_type;
  _armP_type armP;

   typedef float _boomV_type;
  _boomV_type boomV;

   typedef float _armV_type;
  _armV_type armV;

   typedef float _boomI_type;
  _boomI_type boomI;

   typedef float _armI_type;
  _armI_type armI;

   typedef int8_t _boomMode_type;
  _boomMode_type boomMode;

   typedef int8_t _armMode_type;
  _armMode_type armMode;




  typedef boost::shared_ptr< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> const> ConstPtr;

}; // struct JointStateMachineArduino_

typedef ::exp_excavator::JointStateMachineArduino_<std::allocator<void> > JointStateMachineArduino;

typedef boost::shared_ptr< ::exp_excavator::JointStateMachineArduino > JointStateMachineArduinoPtr;
typedef boost::shared_ptr< ::exp_excavator::JointStateMachineArduino const> JointStateMachineArduinoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exp_excavator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'exp_excavator': ['/home/dlab/ros_ws/src/exp_excavator/msg'], 'std_msgs': ['/home/dlab/ros_catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2c69b24e60d81685d15c8dc83d8091c";
  }

  static const char* value(const ::exp_excavator::JointStateMachineArduino_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2c69b24e60d8168ULL;
  static const uint64_t static_value2 = 0x5d15c8dc83d8091cULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_excavator/JointStateMachineArduino";
  }

  static const char* value(const ::exp_excavator::JointStateMachineArduino_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 boomP\n\
float32 armP\n\
\n\
float32 boomV\n\
float32 armV\n\
\n\
float32 boomI\n\
float32 armI\n\
\n\
int8 boomMode\n\
int8 armMode\n\
";
  }

  static const char* value(const ::exp_excavator::JointStateMachineArduino_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boomP);
      stream.next(m.armP);
      stream.next(m.boomV);
      stream.next(m.armV);
      stream.next(m.boomI);
      stream.next(m.armI);
      stream.next(m.boomMode);
      stream.next(m.armMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointStateMachineArduino_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_excavator::JointStateMachineArduino_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_excavator::JointStateMachineArduino_<ContainerAllocator>& v)
  {
    s << indent << "boomP: ";
    Printer<float>::stream(s, indent + "  ", v.boomP);
    s << indent << "armP: ";
    Printer<float>::stream(s, indent + "  ", v.armP);
    s << indent << "boomV: ";
    Printer<float>::stream(s, indent + "  ", v.boomV);
    s << indent << "armV: ";
    Printer<float>::stream(s, indent + "  ", v.armV);
    s << indent << "boomI: ";
    Printer<float>::stream(s, indent + "  ", v.boomI);
    s << indent << "armI: ";
    Printer<float>::stream(s, indent + "  ", v.armI);
    s << indent << "boomMode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.boomMode);
    s << indent << "armMode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.armMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_EXCAVATOR_MESSAGE_JOINTSTATEMACHINEARDUINO_H
