// Generated by gencpp from file exp_excavator/JointCommandDynamixel.msg
// DO NOT EDIT!


#ifndef EXP_EXCAVATOR_MESSAGE_JOINTCOMMANDDYNAMIXEL_H
#define EXP_EXCAVATOR_MESSAGE_JOINTCOMMANDDYNAMIXEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace exp_excavator
{
template <class ContainerAllocator>
struct JointCommandDynamixel_
{
  typedef JointCommandDynamixel_<ContainerAllocator> Type;

  JointCommandDynamixel_()
    : header()
    , bucketV(0.0)
    , bucketP(0.0)  {
    }
  JointCommandDynamixel_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bucketV(0.0)
    , bucketP(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _bucketV_type;
  _bucketV_type bucketV;

   typedef double _bucketP_type;
  _bucketP_type bucketP;




  typedef boost::shared_ptr< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> const> ConstPtr;

}; // struct JointCommandDynamixel_

typedef ::exp_excavator::JointCommandDynamixel_<std::allocator<void> > JointCommandDynamixel;

typedef boost::shared_ptr< ::exp_excavator::JointCommandDynamixel > JointCommandDynamixelPtr;
typedef boost::shared_ptr< ::exp_excavator::JointCommandDynamixel const> JointCommandDynamixelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exp_excavator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'exp_excavator': ['/home/dlab/ros_ws/src/exp_excavator/msg'], 'std_msgs': ['/home/dlab/ros_catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cbe3711ac227927c7f2153f8850e46e";
  }

  static const char* value(const ::exp_excavator::JointCommandDynamixel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cbe3711ac227927ULL;
  static const uint64_t static_value2 = 0xc7f2153f8850e46eULL;
};

template<class ContainerAllocator>
struct DataType< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp_excavator/JointCommandDynamixel";
  }

  static const char* value(const ::exp_excavator::JointCommandDynamixel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 bucketV\n\
float64 bucketP\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::exp_excavator::JointCommandDynamixel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bucketV);
      stream.next(m.bucketP);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointCommandDynamixel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp_excavator::JointCommandDynamixel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp_excavator::JointCommandDynamixel_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bucketV: ";
    Printer<double>::stream(s, indent + "  ", v.bucketV);
    s << indent << "bucketP: ";
    Printer<double>::stream(s, indent + "  ", v.bucketP);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP_EXCAVATOR_MESSAGE_JOINTCOMMANDDYNAMIXEL_H
